services:
  - type: web
    name: jobnest-backend
    env: docker
    dockerfilePath: ./Backend/Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUD_NAME
        value: dqiphllua
      - key: CLOUD_API
        value: 269528767357663
      - key: API_SECRET
        value: Pf11Pb08XrkvOWL5if8U3uMgQSA
      - key: CLIENT_ORIGIN
        value: https://placeholder-frontend.onrender.com
      - key: PORT
        value: 5000
    healthCheckPath: /
    plan: free

  - type: web
    name: jobnest-frontend
    env: docker
    dockerfilePath: ./Frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://placeholder-backend.onrender.com
    plan: free