services:
  - type: web
    name: jobnest-backend
    env: docker
    dockerfilePath: ./Backend/Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API
        sync: false
      - key: API_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        value: https://jobnest-frontend-y6ut.onrender.com
      - key: PORT
        value: 5000
    healthCheckPath: /
    plan: free

  - type: web
    name: jobnest-frontend
    env: docker
    dockerfilePath: ./Frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://jobnest-backend-kcab.onrender.com
    plan: free